trigger:
  - main

pr:
  - main

pool:
  name: 'MyPull'

variables:
  pythonVersion: '3.11'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - powershell: |
      python -m venv .venv
      .venv\Scripts\activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - powershell: |
      .venv\Scripts\activate
      python manage.py migrate --noinput
      if (!(Test-Path -Path reports)) { New-Item -ItemType Directory reports }
      pytest --junitxml=reports/junit.xml --maxfail=1 -q
    displayName: 'Run migrations and tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'reports/junit.xml'
      mergeTestResults: true
    condition: succeededOrFailed()
    displayName: 'Publish test results'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'reports'
      artifact: 'test-reports'
    condition: succeededOrFailed()
    displayName: 'Publish test reports artifact'
